language: ruby
sudo: false

rvm:
  - 2.4.2
script: ./travis.rb

before_install:
  - "travis_retry gem update --system"
  - "gem uninstall bundler --all --ignore-dependencies --executables || true"
  - "bundle --version"
