language: ruby
sudo: false

rvm:
  - 2.4.2
script: ./travis.rb

before_install:
  - "rvm @global do gem uninstall bundler --all --ignore-dependencies --executables || true"
  - "travis_retry gem install bundler -v 1.15.4"
  - "bundle --version"
